[package]
name = "rocket-governor"
version = "2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
governor = "0.4"
lazy_static = "1.4"
